- name: Drop Oracle database
  shell: |
    export ORACLE_SID={{ ORACLE_SID }}
    export ORAENV_ASK=NO
    . /usr/local/bin/oraenv {{ ORACLE_SID }} > /dev/null 2>&1
    dbca -silent -deleteDatabase -sourceDB {{ ORACLE_SID }} -sysDBAUserName sys -sysDBAPassword {{ SYS_PASSWORD }}
  register: dbca_output
  ignore_errors: yes

- debug:
    msg: "Standard Output: {{ dbca_output.stdout }}"

- debug:
    msg: "Standard Error: {{ dbca_output.stderr }}"

- name: Fail if there is an error
  fail:
    msg: "Database drop failed"
  when: dbca_output.rc != 0
