- name: Create Source Listener
  template:
    src: "{{ role_path }}/templates/primary_listener.ora.j2"
    dest: "{{ stage_dir }}/tns/listener.ora"
    mode: 0755
  run_once: true


- name: Create tnsnames.ora
  template:
    src: "{{ role_path }}/templates/tnsnames.ora.j2"
    dest: "{{ stage_dir }}/tns/tnsnames.ora"
    mode: 0755

- name: Start LISTENER_RMAN
  shell: |
      export ORACLE_HOME={{ oracle_home }}
      export PATH=${ORACLE_HOME}/bin:$PATH
      export ORACLE_SID={{ primary_sid }}
      export TNS_ADMIN={{ tns_admin }}
      lsnrctl start LISTENER_RMAN
  register: db_listener

- name: Debug db_listener output
  debug: 
    var: db_listener.stdout_lines 
